language: r
dist: bionic
cache: packages

install:
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_script:
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links || true
