---
title: "Demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2)
library(k3reviews)
```

## Load all reviews

```{r}
df <- get_songs_ratings(get_all_song_filenames())
knitr::kable(head(df))
```

## Count songs and reviews

```{r}
filenames <- unique(df$filename)
n_songs <- length(filenames)
message("Number of songs: ", n_songs)
n_reviewed <- sum(filenames %in% na.omit(df)$filename)
n_unreviewed <- sum(!filenames %in% na.omit(df)$filename)
message("Reviewed: ", n_reviewed)
message("Not reviewed: ", n_unreviewed)
```

## How many reviews have been done?

```{r}
ggplot(na.omit(df), aes(x = formation, fill = reviewer)) +
  geom_histogram(stat = "count")
```


## What are the grades given by the reviewers?

```{r}
df$rating <- as.numeric(df$rating)
ggplot(na.omit(df), aes(x = reviewer , y = rating)) +
  geom_boxplot()
```

## What are the grades given by the reviewers?

```{r}
df$rating <- as.numeric(df$rating)
ggplot(na.omit(df), aes(x = formation , y = rating, fill = reviewer)) +
  geom_boxplot()
```

