#' Obtain the reviews of K3
#' @return a dataframe
#' @export
#' @author Richel Bilderbeek
get_reviews <- function() {

  m <- matrix(ncol = 3, byrow = TRUE,
    data = c(
      "10000 Luchtballonnen", "Richel Bilderbeek", "8",
      "Kusjessoldaten", "Richel Bilderbeek", "8",
      "Als het binnenregent", "Richel Bilderbeek", "8",
      "Jodelee", "Richel Bilderbeek", "7",
      "Kus van de juf", "Richel Bilderbeek", "6",
      "Jij bent de bom!", "Richel Bilderbeek", "7",
      "Rettettet", "Richel Bilderbeek", "1",
      "Lila liedjesland", "Richel Bilderbeek", "6",
      "Woef!", "Richel Bilderbeek", "7",
      "Do do do you love me", "Richel Bilderbeek", "7",
      "Mami Bisou", "Richel Bilderbeek", "5",
      "Meisjesdag", "Richel Bilderbeek", "9",
      "Loko le", "Richel Bilderbeek", "6",
      "Eya hoya!", "Richel Bilderbeek", "1",
      "Eya hoya!", "Mark Wiering", "0",
      "Viva viool", "Richel Bilderbeek", "7",
      "Kusje van jou", "Richel Bilderbeek", "7.5",
      "Drums gaan boem", "Richel Bilderbeek", "3",
      "En ik dans", "Richel Bilderbeek", "9",
      "Alleen door jou", "Richel Bilderbeek", "9",
      "Ik wil niet naar huis gaan", "Richel Bilderbeek", "8",
      "Het steltenlied", "Richel Bilderbeek", "8",
      "Wat jij doet met mij", "Richel Bilderbeek", "6",
      "Kitty", "Richel Bilderbeek", "7",
      "Kinderen baas", "Richel Bilderbeek", "9",
      "Koning Willem-Alexander", "Richel Bilderbeek", "7",
      "Waar zijn die engeltjes", "Richel Bilderbeek", "9",
      "Zeg eens AAA", "Richel Bilderbeek", "8",
      "Parapluutje", "Richel Bilderbeek", "8",
      "Mama kan alles", "Richel Bilderbeek", "8",
      "Vind ik leuk", "Richel Bilderbeek", "5",
      "Leugentje leugentje", "Richel Bilderbeek", "4",
      "Wie zal ik een kusje geven", "Richel Bilderbeek", "9",
      "Niet normaal", "Richel Bilderbeek", "7",
      "Gigaleuke dag", "Richel Bilderbeek", "4",
      "Jurkje", "Richel Bilderbeek", "7.5",
      "Zwaai als je verliefd bent", "Richel Bilderbeek", "8.5",
      "Mijn liefje achterna", "Richel Bilderbeek", "7.5",
      "Eyo!", "Richel Bilderbeek", "6",
      "Hallo K3", "Richel Bilderbeek", "9",
      "Willem-Alexander", "Richel Bilderbeek", "7.5",
      "Smoorverliefd", "Richel Bilderbeek", "4",
      "K3-Airlines", "Richel Bilderbeek", "8",
      "Beroemd", "Richel Bilderbeek", "6",
      "Beroemd", "Richel Bilderbeek", "6",
      "Meiden van de brandweer", "Richel Bilderbeek", "7",
      "Verstoppertje", "Richel Bilderbeek", "6",
      "Telepathie", "Richel Bilderbeek", "7",
      "Dubbeldekkertrein", "Richel Bilderbeek", "4",
      "Bel me ringeling", "Richel Bilderbeek", "7",
      "Cowboys en indianen", "Richel Bilderbeek", "7",
      "MaMaSe", "Richel Bilderbeek", "7",
      "De politie", "Richel Bilderbeek", "7",
      "Handjes draaien", "Richel Bilderbeek", "1",
      "Leukste van het land", "Richel Bilderbeek", "5",
      "Lollypopland", "Richel Bilderbeek", "4",
      "De revolutie", "Richel Bilderbeek", "8",
      "Hiep hiep hoera", "Richel Bilderbeek", "4",
      "Radio", "Richel Bilderbeek", "8",
      "Blankenberge", "Richel Bilderbeek", "9",
      "Hey hey", "Richel Bilderbeek", "4",
      "Ster", "Richel Bilderbeek", "6",
      "Wanneer zie ik jou terug", "Richel Bilderbeek", "8",
      "Kusjesdag", "Richel Bilderbeek", "8",
      "Je mama ziet je graag", "Richel Bilderbeek", "5",
      "Billy Billy", "Mark Wiering", "5.6",
      "Billy Billy", "Richel Bilderbeek", "8",
      "Sterren", "Richel Bilderbeek", "7",
      "Jongen van mijn dromen", "Richel Bilderbeek", "6",
      "Ons huis", "Richel Bilderbeek", "5",
      "Iedereen op de dansvloer", "Richel Bilderbeek", "4",
      "De wereld veranderen", "Richel Bilderbeek", "6",
      "Sproetje", "Richel Bilderbeek", "5",
      "Prinses", "Richel Bilderbeek", "7",
      "Vliegen als een vogel", "Richel Bilderbeek", "6",
      "Ware liefde", "Mark Wiering", "8",
      "Ware liefde", "Richel Bilderbeek", "8",
      "Ya Ya Yippee", "Richel Bilderbeek", "9",
      "Dokter Dokter", "Richel Bilderbeek", "9",
      "Trouwen", "Richel Bilderbeek", "9",
      "Zoo", "Richel Bilderbeek", "2",
      "Eskimo", "Richel Bilderbeek", "2",
      "Sprookjesbos", "Richel Bilderbeek", "6",
      "Bibliotheek", "Richel Bilderbeek", "7",
      "Feestje", "Richel Bilderbeek", "5",
      "Op Televisie", "Richel Bilderbeek", "6",
      "Excuseer Me", "Mark Wiering", "7.7",
      "Excuseer Me", "Richel Bilderbeek", "4",
      "Vriendschap", "Richel Bilderbeek", "6",
      "Eeny Meeny", "Mark Wiering", "7.4",
      "Eeny Meeny", "Richel Bilderbeek", "4"
    )
  )

  df <- data.frame(m, stringsAsFactors = FALSE)
  names(df) <- c("song_name", "reviewer_name", "grade")
  df$song_name <- as.factor(df$song_name)
  df$reviewer_name <- as.factor(df$reviewer_name)
  df$grade <- as.numeric(df$grade)
  df
}
