#' Obtain the discography of K3
#' @return a datafrm
#' @export
#' @author Richel Bilderbeek
get_discography <- function() {

  m <- matrix(ncol = 3, byrow = TRUE,
    data = c(
      "10000 Luchtballonnen",  "1", "10000 Luchtballonnen",
      "10000 Luchtballonnen",  "2", "Kusjessoldaten",
      "10000 Luchtballonnen",  "3", "Als het binnenregent",
      "10000 Luchtballonnen",  "4", "Jodelee",
      "10000 Luchtballonnen",  "5", "Kus van de juf",
      "10000 Luchtballonnen",  "6", "Jij bent de bom!",
      "10000 Luchtballonnen",  "7", "Rettettet",
      "10000 Luchtballonnen",  "8", "Lila liedjesland",
      "10000 Luchtballonnen",  "9", "Woef!",
      "10000 Luchtballonnen", "10", "Do do do you love me",
      "10000 Luchtballonnen", "11", "Mami Bisou",
      "10000 Luchtballonnen", "12", "Meisjesdag",
      "Loko Le",  "1", "Loko le",
      "Loko Le",  "2", "Eya hoya!",
      "Loko Le",  "3", "Viva viool",
      "Loko Le",  "4", "Kusje van jou",
      "Loko Le",  "5", "Drums gaan boem",
      "Loko Le",  "6", "En ik dans",
      "Loko Le",  "7", "Alleen door jou",
      "Loko Le",  "8", "Ik wil niet naar huis gaan",
      "Loko Le",  "9", "Het steltenlied",
      "Loko Le", "10", "Wat jij doet met mij",
      "Loko Le", "11", "Kitty",
      "Loko Le", "12", "Kinderen baas",
      "Loko Le", "13", "Koning Willem-Alexander",
      "Engeltjes", "1", "Waar zijn die engeltjes",
      "Engeltjes", "2", "Zeg eens AAA",
      "Engeltjes", "3", "Parapluutje",
      "Engeltjes", "4", "Mama kan alles",
      "Engeltjes", "5", "Vind ik leuk",
      "Engeltjes", "6", "Leugentje leugentje",
      "Engeltjes", "7", "Wie zal ik een kusje geven",
      "Engeltjes", "8", "Niet normaal",
      "Engeltjes", "9", "Gigaleuke dag",
      "Engeltjes", "0", "Jurkje",
      "Engeltjes", "1", "Zwaai als je verliefd bent",
      "Engeltjes", "12", "Mijn liefje achterna",
      "Eyo",  "1", "Eyo!",
      "Eyo",  "2", "Hallo K3",
      "Eyo",  "3", "Willem-Alexander",
      "Eyo",  "4", "Smoorverliefd",
      "Eyo",  "5", "K3-Airlines",
      "Eyo",  "6", "Beroemd",
      "Eyo",  "7", "Meiden van de brandweer",
      "Eyo",  "8", "Verstoppertje",
      "Eyo",  "9", "Telepathie",
      "Eyo", "10", "Dubbeldekkertrein",
      "Eyo", "11", "Bel me ringeling",
      "Eyo", "12", "Cowboys en indianen",
      "MaMaSe",  "1", "MaMaSe",
      "MaMaSe",  "2", "De politie",
      "MaMaSe",  "3", "Handjes draaien",
      "MaMaSe",  "4", "Leukste van het land",
      "MaMaSe",  "5", "Lollypopland",
      "MaMaSe",  "6", "De revolutie",
      "MaMaSe",  "7", "Hiep hiep hoera",
      "MaMaSe",  "8", "Radio",
      "MaMaSe",  "9", "Blankenberge",
      "MaMaSe", "10", "Hey hey",
      "MaMaSe", "11", "Ster",
      "MaMaSe", "12", "Wanneer zie ik jou terug",
      "Kusjes",  "1", "Kusjesdag",
      "Kusjes",  "2", "Je mama ziet je graag",
      "Kusjes",  "3", "Billy Billy",
      "Kusjes",  "4", "Sterren",
      "Kusjes",  "5", "Jongen van mijn dromen",
      "Kusjes",  "6", "Ons huis",
      "Kusjes",  "7", "Iedereen op de dansvloer",
      "Kusjes",  "8", "De wereld veranderen",
      "Kusjes",  "9", "Sproetje",
      "Kusjes", "10", "Prinses",
      "Kusjes", "11", "Vliegen als een vogel",
      "Kusjes", "12", "Ware liefde",
      "Ya ya yippee",  "1", "Ya Ya Yippee",
      "Ya ya yippee",  "2", "Dokter Dokter",
      "Ya ya yippee",  "3", "Trouwen",
      "Ya ya yippee",  "4", "Zoo",
      "Ya ya yippee",  "5", "Eskimo",
      "Ya ya yippee",  "6", "Sprookjesbos",
      "Ya ya yippee",  "7", "Bibliotheek",
      "Ya ya yippee",  "8", "Feestje",
      "Ya ya yippee",  "9", "Op Televisie",
      "Ya ya yippee", "10", "Excuseer Me",
      "Ya ya yippee", "11", "Vriendschap",
      "Ya ya yippee", "12", "Eeny Meeny"
    )
  )

  df <- data.frame(m)
  names(df) <- c("cd_title", "track_number", "song_name")

  df
}
